export const languages = [
  { name: "Afrikaans", langCode: "af", flagCode: "ZA" },
  { name: "Albanian", langCode: "sq", flagCode: "AL" },
  { name: "Amharic", langCode: "am", flagCode: "ET" },
  { name: "Arabic", langCode: "ar", flagCode: "" },
  { name: "Armenian", langCode: "hy", flagCode: "AM" },
  { name: "Azerbaijani", langCode: "az", flagCode: "AZ" },
  { name: "Bengali", langCode: "bn", flagCode: "BD" },
  { name: "Bosnian", langCode: "bs", flagCode: "BA" },
  { name: "Bulgarian", langCode: "bg", flagCode: "BG" },
  { name: "Catalan", langCode: "ca", flagCode: "" },
  { name: "Chinese (Simplified)", langCode: "zh", flagCode: "CN" },
  { name: "Chinese (Traditional)", langCode: "zh-TW", flagCode: "CN" },
  { name: "Croatian", langCode: "hr", flagCode: "HR" },
  { name: "Czech", langCode: "cs", flagCode: "CZ" },
  { name: "Danish", langCode: "da", flagCode: "DK" },
  { name: "Dari", langCode: "fa-AF", flagCode: "AF" },
  { name: "Dutch", langCode: "nl", flagCode: "NL" },
  { name: "English", langCode: "en", flagCode: "GB-ENG" },
  { name: "Estonian", langCode: "et", flagCode: "EE" },
  { name: "Farsi (Persian)", langCode: "fa", flagCode: "IR" },
  { name: "Filipino, Tagalog", langCode: "tl", flagCode: "PH" },
  { name: "Finnish", langCode: "fi", flagCode: "FI" },
  { name: "French", langCode: "fr", flagCode: "FR" },
  { name: "French (Canada)", langCode: "fr-CA", flagCode: "CA" },
  { name: "Georgian", langCode: "ka", flagCode: "GE" },
  { name: "German", langCode: "de", flagCode: "DE" },
  { name: "Greek", langCode: "el", flagCode: "GR" },
  { name: "Gujarati", langCode: "gu", flagCode: "IN" },
  { name: "Haitian Creole", langCode: "ht", flagCode: "HT" },
  { name: "Hausa", langCode: "ha", flagCode: "NG" },
  { name: "Hebrew", langCode: "he", flagCode: "IL" },
  { name: "Hindi", langCode: "hi", flagCode: "IN" },
  { name: "Hungarian", langCode: "hu", flagCode: "HU" },
  { name: "Icelandic", langCode: "is", flagCode: "IS" },
  { name: "Indonesian", langCode: "id", flagCode: "ID" },
  { name: "Irish", langCode: "ga", flagCode: "IE" },
  { name: "Italian", langCode: "it", flagCode: "IT" },
  { name: "Japanese", langCode: "ja", flagCode: "JP" },
  { name: "Kannada", langCode: "kn", flagCode: "IN" },
  { name: "Kazakh", langCode: "kk", flagCode: "KZ" },
  { name: "Korean", langCode: "ko", flagCode: "KR" },
  { name: "Latvian", langCode: "lv", flagCode: "LV" },
  { name: "Lithuanian", langCode: "lt", flagCode: "LT" },
  { name: "Macedonian", langCode: "mk", flagCode: "MK" },
  { name: "Malay", langCode: "ms", flagCode: "MY" },
  { name: "Malayalam", langCode: "ml", flagCode: "IN" },
  { name: "Maltese", langCode: "mt", flagCode: "MT" },
  { name: "Marathi", langCode: "mr", flagCode: "IN" },
  { name: "Mongolian", langCode: "mn", flagCode: "MN" },
  { name: "Norwegian", langCode: "no", flagCode: "NO" },
  { name: "Pashto", langCode: "ps", flagCode: "IR" },
  { name: "Polish", langCode: "pl", flagCode: "PL" },
  { name: "Portuguese (Brazil)", langCode: "pt", flagCode: "BR" },
  { name: "Portuguese (Portugal)", langCode: "pt-PT", flagCode: "PT" },
  { name: "Punjabi", langCode: "pa", flagCode: "" },
  { name: "Romanian", langCode: "ro", flagCode: "RO" },
  { name: "Russian", langCode: "ru", flagCode: "RU" },
  { name: "Serbian", langCode: "sr", flagCode: "RS" },
  { name: "Sinhala", langCode: "si", flagCode: "" },
  { name: "Slovak", langCode: "sk", flagCode: "SK" },
  { name: "Slovenian", langCode: "sl", flagCode: "SI" },
  { name: "Somali", langCode: "so", flagCode: "SO" },
  { name: "Spanish", langCode: "es", flagCode: "ES" },
  { name: "Spanish (Mexico)", langCode: "es-MX", flagCode: "MX" },
  { name: "Swahili", langCode: "sw", flagCode: "KE" },
  { name: "Swedish", langCode: "sv", flagCode: "SE" },
  { name: "Tamil", langCode: "ta", flagCode: "" },
  { name: "Telugu", langCode: "te", flagCode: "" },
  { name: "Thai", langCode: "th", flagCode: "TH" },
  { name: "Turkish", langCode: "tr", flagCode: "TR" },
  { name: "Ukrainian", langCode: "uk", flagCode: "UA" },
  { name: "Urdu", langCode: "ur", flagCode: "" },
  { name: "Uzbek", langCode: "uz", flagCode: "UZ" },
  { name: "Vietnamese", langCode: "vi", flagCode: "VN" },
  { name: "Welsh", langCode: "cy", flagCode: "GB-WLS" },
];
